### ISSUE TITLE
请问例子中为什么在页面末尾多出来几个input？

### ISSUE THREAD

**Issue by hzjianglf** [hillpy/easyUploader#1]
如：
<input type="file" name="file" id="easyuploader_nuiExIPbY3q9bWKt" accept="" style="display: none; !important">

会影响表单的提交，请问可以去掉吗？谢谢

**Comment by hzjianglf** [comment]
请见：`<input type="file" name="file" id="easyuploader_nuiExIPbY3q9bWKt" accept="" style="display: none; !important">`

**Comment by shinn-lancelot** [comment]
感谢您的提问~ 关于这个问题：若绑定到元素节点（el选项），在初始化时会创建input。位置可以考虑调整，去掉就影响上传功能了。

修改方式

1. 你可以考虑自己编写input，在初始化时绑定到input上（去掉"el"选项，添加"file"选项）。

2. 修改表单上传方式（将表单元素放在form元素中，序列化表单并ajax提交）。

我想这样应该可以解决问题。
